x-dns-settings: &default-dns
  dns:
    - 1.1.1.1
    - 8.8.8.8

networks:
  services_net:
    driver: bridge

services:
  home:
    image: ghcr.io/gethomepage/homepage:v1.11
    container_name: homepage
    <<: *default-dns
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.kamuridesu.com,home.internal
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - services_net
    volumes:
      - ${HOMEPAGE_CONFIG}:/app/config
    ports:
      - 3000:3000
    restart: unless-stopped

  pluto_api:
    container_name: pluto-api
    image: quay.io/kamuridesu/pluto-playlist-api
    <<: *default-dns
    restart: unless-stopped
    environment:
      - TZ_INFO=${TZ_INFO}
      - TOTAL_DELAY_SECONDS=86400
    networks:
      - services_net
    ports:
      - 3002:3000
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 200M

  go_anilist:
    container_name: go-anilist-ical
    image: kamuri/go-anilist-ical:1.0.0
    <<: *default-dns
    restart: unless-stopped
    networks:
      - services_net
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 100M

  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    restart: unless-stopped
    <<: *default-dns
    environment:
      - TZ=${TZ_INFO}
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    networks:
      - services_net
    volumes:
      - ${FORGEJO_CONFIG}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3000
      - 222:22

  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard
    restart: unless-stopped
    <<: *default-dns
    networks:
      - services_net
    volumes:
      - ${ADGUARD_WD}:/opt/adguardhome/work
      - ${ADGUARD_CONFIG}:/opt/adguardhome/conf
    ports:
      - 53:53/udp
      - 53:53/tcp
      # - 67:67/udp
      # - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3003:3000/tcp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      # - 6060:6060/tcp
      #

  readeck:
    image: codeberg.org/readeck/readeck:0.22.3
    container_name: readeck
    restart: unless-stopped
    <<: *default-dns
    env_file: .env
    networks:
      - services_net
    volumes:
      - ${READECK_CONFIG}:/readeck
    ports:
      - 8000:8000
